Adding time difference route
KGmajor/practical_prep pull request #2
Opened 2021-02-23 01:06 UTC by KGmajor

Things to do:
Add a new route that displays the time differences between two timezones. 

How to test:
http://0.0.0.0:5000/time-difference?here=America/Chicago&there=America/Denver

2021-02-23 23:21 UTC, courtneycodes95 requested changes
Great job overall! The route accomplishes exactly what it needs to and the error messages are very helpful. I left a few suggestions for you to take a look at.

2021-02-23 23:21 UTC, courtneycodes95 commented on app.py
> +from dateutil.relativedelta import relativedelta
Remember to update the README to include dateutil under Applicable Documentation.

2021-02-23 23:21 UTC, courtneycodes95 commented on app.py
> +def time_diff():
It might be helpful to add your note about how to test the route in a comment here for others reading the code directly.

2021-02-23 23:21 UTC, courtneycodes95 commented on app.py
> +    try:
Great use of error handling!

2021-02-23 23:21 UTC, courtneycodes95 commented on app.py
> +        u = pytz.timezone('utc').localize(datetime.utcnow())
Lines 61 to 63 are a little hard to follow. Can we use different variable names to describe the transformations that are happening?

2021-06-23 23:02 UTC, KGmajor commented on app.py
> +    try:
The pattern of this api seems to have docstrings, I suggest adding one to make it easier to tell what this does.

2021-06-23 23:04 UTC, KGmajor commented on app.py
> +@app.route('/time-difference', methods=['GET', 'POST','PUT'])
I'm confused about the multiple request methods, should they all be accepted here?

2021-06-23 23:07 UTC, KGmajor commented on app.py
> +            h = request.args.get('here')
I think that 'here' and 'there' are a little confusing, I suggest maybe 'timezone1' and 'timezone2'

2021-06-23 23:07 UTC, KGmajor commented on app.py
> +        u = pytz.timezone('utc').localize(datetime.utcnow())
I think it might be more clear if 'u' was a bit more descriptive of the result.

2026-03-29 05:02 UTC, closed without merging

2026-10-06 22:12 UTC, emberseason commented
Hi @KGmajor, I noticed your `practical_prep` thread adding a time-difference route.
Your Python work makes your skills a plausible fit for my business, and I’m impressed by your experience as a software engineer and Chief Strategy Officer at YearOne.
I’m currently looking for a contributor to help with my business in a part-time collaboration that provides great side income; if interested, please contact via [this email](mailto:hector624@proton.me).